// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUkeqYNVmsYNeZ95N_O7Z3o6CRw_61vs',
    appId: '1:260684116256:android:954226e596465f5b81a745',
    messagingSenderId: '260684116256',
    projectId: 'flutter-instagram-clone2',
    storageBucket: 'flutter-instagram-clone2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbWAhUHYYOdY7aIO0bCRtOXYFga6UCDpg',
    appId: '1:260684116256:ios:c2a889ffec2c3f2981a745',
    messagingSenderId: '260684116256',
    projectId: 'flutter-instagram-clone2',
    storageBucket: 'flutter-instagram-clone2.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOu6blxZS6OAeelKBD1Z7ph2zwF1UFXpo',
    appId: '1:260684116256:web:e53eb44541c5d67181a745',
    messagingSenderId: '260684116256',
    projectId: 'flutter-instagram-clone2',
    authDomain: 'flutter-instagram-clone2.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone2.appspot.com',
  );

}